version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./MoviesReview/backend
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./MoviesReview/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./MoviesReview/frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: